/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.logging.Level;

public class Interface extends javax.swing.JFrame {
   
    private CadenasJeu jeu;
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Victoire
     */
    public Interface() {
        initComponents();
        jeu = new CadenasJeu();
        texte_score.setText(jeu.getTentativesEffectuees() + " sur " + jeu.getMaxTentatives());
        texte_intro.setText("Trouvez le bon code en moins de " + jeu.getMaxTentatives() + " tentatives !");
    }
   
    private void mettreAJourChiffre(javax.swing.JLabel label, boolean increment) {
        if (jeu.estPartieTerminee()) {
            return;
        }
       
        try {
            int chiffre = Integer.parseInt(label.getText());
            if (increment) {
                chiffre = (chiffre + 1) % 10;
            } else {
                chiffre = (chiffre - 1 + 10) % 10;
            }
            label.setText(String.valueOf(chiffre));
        } catch (NumberFormatException e) {
            label.setText("0");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_chiffres_bas = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        texte_lbl_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texte_intro.setForeground(new java.awt.Color(255, 0, 255));
        texte_intro.setText("Trouvez le bon code en moins de 5 tentatives");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 27, 320, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 73, 80, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 73, 80, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 73, 80, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 73, 80, -1));

                        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_0.setForeground(new java.awt.Color(255, 0, 51));
                        texte_chiffre_0.setText("0");
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 114, -1, -1));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_1.setForeground(new java.awt.Color(255, 51, 51));
                        texte_chiffre_1.setText("0");
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 114, -1, -1));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_2.setForeground(new java.awt.Color(255, 51, 51));
                        texte_chiffre_2.setText("0");
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 114, -1, -1));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_3.setForeground(new java.awt.Color(255, 51, 51));
                        texte_chiffre_3.setText("0");
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 27, 54));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 188, 80, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 188, 80, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 80, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 188, 80, -1));

                        bouton_tester.setForeground(new java.awt.Color(51, 255, 255));
                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 137, -1, -1));

                        texte_lbl_chiffres_exacts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                        texte_lbl_chiffres_exacts.setText("nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 229, -1, -1));

                        texte_nb_chiffres_exacts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                        texte_nb_chiffres_exacts.setForeground(new java.awt.Color(0, 255, 0));
                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 229, -1, -1));

                        texte_lbl_chiffres_bas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                        texte_lbl_chiffres_bas.setText("nombre de chiffre plus bas :");
                        getContentPane().add(texte_lbl_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 299, -1, -1));

                        bouton_recommencer.setText("recommencez");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 302, -1, -1));

                        texte_lbl_chiffres_haut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                        texte_lbl_chiffres_haut.setText("nombre de chiffres plus hauts :");
                        getContentPane().add(texte_lbl_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 267, -1, -1));

                        texte_nb_chiffres_haut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                        texte_nb_chiffres_haut.setForeground(new java.awt.Color(0, 153, 153));
                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 267, -1, -1));

                        texte_nb_chiffres_bas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                        texte_nb_chiffres_bas.setForeground(new java.awt.Color(255, 0, 0));
                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 299, -1, -1));

                        texte_tentatives.setText("Tentatives : ");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 232, -1, -1));

                        texte_score.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                        texte_score.setForeground(new java.awt.Color(0, 255, 0));
                        texte_score.setText("0 Sur 5");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 255, -1, 30));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
    mettreAJourChiffre(texte_chiffre_0, true);        // TODO add your handling code here: 
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
    mettreAJourChiffre(texte_chiffre_2, true);        // TODO add your handling code here:
       
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
    mettreAJourChiffre(texte_chiffre_1, false);        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
    mettreAJourChiffre(texte_chiffre_3, false);      // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
    mettreAJourChiffre(texte_chiffre_1, true);        // TODO add your handling code here:
       
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
    mettreAJourChiffre(texte_chiffre_2, false);        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
jeu.démarrerJeu();

        texte_chiffre_0.setText("0");
        texte_chiffre_1.setText("0");
        texte_chiffre_2.setText("0");
        texte_chiffre_3.setText("0");

        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_haut.setText("0");
        texte_nb_chiffres_bas.setText("0");

        texte_score.setText(jeu.getTentativesEffectuees() + " sur " + jeu.getMaxTentatives());
       
        bouton_tester.setEnabled(true);
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
    mettreAJourChiffre(texte_chiffre_3, true);        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
    mettreAJourChiffre(texte_chiffre_0, false);        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
if (jeu.estPartieTerminee()) {
            return;
        }

        int[] essai = new int[4];
        try {
            essai[0] = Integer.parseInt(texte_chiffre_0.getText());
            essai[1] = Integer.parseInt(texte_chiffre_1.getText());
            essai[2] = Integer.parseInt(texte_chiffre_2.getText());
            essai[3] = Integer.parseInt(texte_chiffre_3.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erreur: Les chiffres ne sont pas au format attendu.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int[] resultats = jeu.testerCombinaison(essai);
        texte_nb_chiffres_exacts.setText(String.valueOf(resultats[0]));
        texte_nb_chiffres_haut.setText(String.valueOf(resultats[1]));
        texte_nb_chiffres_bas.setText(String.valueOf(resultats[2]));
        texte_score.setText(jeu.getTentativesEffectuees() + " sur " + jeu.getMaxTentatives());

        if (jeu.estPartieTerminee()) {
            bouton_tester.setEnabled(false);
            String message;
            if (jeu.estGagne()) {
                message = "Bravo Vous avez trouvé le code secret : " + jeu.getCodeSecretString();
            } else {
                message = "Perdu  Le code  était : " + jeu.getCodeSecretString();
            }
            JOptionPane.showMessageDialog(this, message, "Fin de partie", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_chiffres_bas;
    private javax.swing.JLabel texte_lbl_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
