/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fenetre_quiz;

import java.util.ArrayList;
import java.awt.EventQueue;

/**
 *
 * @author ADMIN
 */
public class fenetre_quiz extends javax.swing.JFrame {
    
    private ArrayList<Question> listeQuestion = new ArrayList<>();
    private int indexQuestionCourante = 0;
    private int score = 0;

    public fenetre_quiz() {
        initComponents();
        initQuestion();
        afficherQuestionCourante();
    }

    private void initQuestion() {

        listeQuestion.add(new Question(
                "Quelle est la capitale de la France ?",
                "Berlin", "Paris", "Rome", "Madrid", 2));

        listeQuestion.add(new Question(
                "5 x 3 = ?",
                "10", "15", "20", "25", 2));

        listeQuestion.add(new Question(
                "Planète rouge ?",
                "Vénus", "Mars", "Jupiter", "Saturne", 2));

        listeQuestion.add(new Question(
                "Langage Android ?",
                "PHP", "Java", "Python", "HTML", 2));

        listeQuestion.add(new Question(
                "2 + 8 = ?",
                "6", "8", "9", "10", 4));
    }

    private void afficherQuestionCourante() {

        Question q = listeQuestion.get(indexQuestionCourante);

        lblQuestion.setText(q.getIntitule());
        btnRep1.setText(q.getProposition1());
        btnRep2.setText(q.getProposition2());
        btnRep3.setText(q.getProposition3());
        btnRep4.setText(q.getProposition4());

        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);

        lblFeedback.setText("");
        lblFeedback.setText("Score : " + score);
    }

    private void traiterReponse(int choix) {

        Question q = listeQuestion.get(indexQuestionCourante);

        if (choix == q.getIndexBonneReponse()) {
            lblFeedback.setText(" Bonne réponse !");
            score++;
        } else {
            lblFeedback.setText(" Mauvaise réponse");
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);

        lblFeedback.setText("Score : " + score);
    }



    /**
     * Creates new form java
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFeedback = new javax.swing.JLabel();
        btnSuivant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setText("jLabel1");

        btnRep1.setText("jButton1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("jButton2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("jButton3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("jButton4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        lblFeedback.setText("jLabel3");

        btnSuivant.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(btnRep4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRep3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRep2)))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lblQuestion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFeedback)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuivant))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFeedback)
                .addGap(37, 37, 37)
                .addComponent(lblQuestion)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep1)
                    .addComponent(btnRep4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep3)
                    .addComponent(btnRep2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSuivant)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed


        indexQuestionCourante++;

        if (indexQuestionCourante < listeQuestion.size()) {
            afficherQuestionCourante();
        } else {
            lblQuestion.setText("Quiz terminé !");
            lblFeedback.setText("Score final : " + score + " / " + listeQuestion.size());
            btnSuivant.setEnabled(false);
        }
    
        
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
 traiterReponse(1);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
 traiterReponse(3);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
 traiterReponse(4);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRep4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(fenetre_quiz.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue
.invokeLater(() -> new fenetre_quiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables

    private static class awt {

        public awt() {
        }
    }
}
